services:
  brokr:
    build: .
    container_name: brokr_app
    ports:
      - "8000:8000"  # Adjust as needed
    environment:
      - API_BASE_URL=https://api.example.com
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app  # Optional, for live updates during development
